version: '3.9'

services:
  api:
    build: .
    container_name: bmi-calculator
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      bmi-calculator-network:
    depends_on:
      - database

  database:
    image: mysql:9.1.0
    container_name: bmi-calculator-database
    environment:
      MYSQL_HOST: database
      MYSQL_USER: bmi_calculator
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: bmi_calculator
    ports:
      - "3306:3306"
    networks:
      bmi-calculator-network:
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=12345678"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  bmi-calculator-network:
    driver: bridge

volumes:
  db_data:
    driver: local
